# Generated by Django 2.1.3 on 2018-11-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '月報', 'verbose_name_plural': '月報'},
        ),
    ]
