# Generated by Django 2.1.3 on 2018-11-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosreport', '0002_auto_20181113_0354'),
    ]
