# Generated by Django 2.1.3 on 2018-11-13 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosreport', '0003_item_mtl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'レポート', 'verbose_name_plural': 'レポート'},
        ),
        migrations.AddField(
            model_name='item',
            name='yyyymm',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(6)], verbose_name='提出年月'),
        ),
        migrations.AlterField(
            model_name='item',
            name='projectstatus',
            field=models.TextField(max_length=300, verbose_name='案件状況'),
        ),
    ]
